Profile
Yannieck/Project5.2-Zweeloo-Web pull request #16
Opened 2023-01-04 13:30 UTC by Yannieck

2023-01-04 14:16 UTC, FrancaBaars requested changes

2023-01-04 14:16 UTC, FrancaBaars commented on web/views/profile.pug
> +                            input(type="password" value="Testtest1!" name="newPass").block.p-1.font-normal.w-full.mb-4
Value hier weghalen niet heel handig

2023-01-04 14:16 UTC, FrancaBaars commented on web/views/profile.pug
> +                            input(type="password" value="Testtest1!" name="newPassRepeat").block.p-1.font-normal.w-full.mb-4
Hier ook

2023-01-04 14:16 UTC, FrancaBaars commented on web/views/profile.pug
> +                .px-16.w-full
op regel 4 staat index dit graag veranderen naar de titel van de pagina :)

2023-01-04 14:16 UTC, FrancaBaars commented on web/views/profile-overview.pug
> +        include head.pug
nog even overleggen of we deze pagina willen

2023-01-04 14:16 UTC, FrancaBaars commented on web/views/profile-overview.pug
> +        title index
als we de pagina houden dit graag veranderen naar de titel van de pagina

2023-01-05 08:24 UTC, FrancaBaars requested changes
Graag nog veranderen dat de gegevens ook geupdate worden op de website zelf, als ik ze nu aanpas dan veranderen ze in de database maar niet op de profiel pagina.

2023-01-05 10:27 UTC, Yannieck commented on web/views/profile.pug
> +                            input(type="password" value="Testtest1!" name="newPass").block.p-1.font-normal.w-full.mb-4
Zo hoor je text de doen in een submit button?

2023-01-05 10:29 UTC, Yannieck commented on web/views/profile.pug
> +                            input(type="password" value="Testtest1!" name="newPass").block.p-1.font-normal.w-full.mb-4
lm gaat over de password field of niet

2023-01-05 12:36 UTC, FrancaBaars requested changes
Paar kleine dingen

2023-01-05 12:36 UTC, FrancaBaars commented on web/middleware/db_object_creator.js
> +
hier nog zo'n fancy comment boven graag

2023-01-05 12:36 UTC, FrancaBaars commented on web/middleware/db_object_creator.js
> +
Hier ook graag een fancy comment

2023-01-05 12:36 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        redirect: "/profiles",},
haakje moet een enter ervoor hebben

2023-01-05 12:36 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        redirect: "/profiles",},
hier ook

2023-01-05 12:36 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        redirect: "/profiles",},
hier ook

2023-01-06 08:32 UTC, FrancaBaars requested changes
paar kleine dingen

2023-01-06 08:32 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        title: "Wachtwoord kon niet worden angepast",
2 a's graag in aangepast

2023-01-06 08:32 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        title: "Onbekende fout opgrtreden",
opgetreden is fout getypt

2023-01-06 08:32 UTC, FrancaBaars commented on web/config/authservice.js
> +                console.log(valid);
hier staat nog een console.log

2023-01-06 08:32 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        text: "U zal nu worden doorgestuurd naar het sponsor overzicht",
een punt achter de zin graag.

2023-01-09 08:48 UTC, FrancaBaars approved these changes

2023-01-09 09:07 UTC, merged