RouteInfoEditor
Yannieck/Project5.2-Zweeloo-Web pull request #6
Opened 2022-12-02 10:01 UTC by Yannieck

Route informatie toevoegen pagina gemaakt en verwerkt in de website.

2022-12-02 13:56 UTC, FrancaBaars requested changes
Nog een aantal dingen veranderen

2022-12-02 13:56 UTC, FrancaBaars commented on web/bin/db_route_controller.js
> +            const distance = 10;
Waarom is dit 10?

2022-12-02 13:56 UTC, FrancaBaars commented on web/middleware/JSONValidator.js
> +        //Check if there is a gpx file
Zou ik veranderen naar "Check if there is a file"

2022-12-02 13:56 UTC, FrancaBaars commented on web/middleware/schemas.js
> +                                Joi.number().min(0).max(360)
Hier moet nog Joi.number() achter

2022-12-02 13:56 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
>  const messages = {
Graag punt aan het einde van iedere zin doen

2022-12-02 13:56 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
>          title: "Account succesvol aangemaakt",
Regel 11 moet worden: "Account kon niet worden aangemaakt" Er moet een t nog achter

2022-12-02 13:56 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
>          text: "U zal nu worden doorgestuurd naar de aanmeld pagina",
Regel 29 graag e-mail met een kleine letter

2022-12-02 13:56 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        title: "Er is geen GPX bestand geupload",
Kan er een ü komen te staan in geüpload?

2022-12-04 19:16 UTC, FrancaBaars commented on web/middleware/JOIValidator.js
>  //JOI DOCS:
Graag op een veilig wachtwoord controleren

2022-12-05 11:47 UTC, Yannieck commented on web/public/assets/scripts/swal.js
>          title: "Account succesvol aangemaakt",
👍

2022-12-05 11:47 UTC, Yannieck commented on web/public/assets/scripts/swal.js
>  const messages = {
👍

2022-12-05 11:47 UTC, Yannieck commented on web/public/assets/scripts/swal.js
>          text: "U zal nu worden doorgestuurd naar de aanmeld pagina",
👍

2022-12-05 11:48 UTC, Yannieck commented on web/public/assets/scripts/swal.js
> +        title: "Er is geen GPX bestand geupload",
👍

2022-12-05 14:42 UTC, Yannieck reviewed
Worked on pull request feedback

2022-12-06 10:55 UTC, FrancaBaars approved these changes

2022-12-06 10:56 UTC, merged