AddRoutePageThree
Yannieck/Project5.2-Zweeloo-Web pull request #8
Opened 2022-12-15 09:53 UTC by Yannieck

2022-12-15 14:48 UTC, FrancaBaars requested changes
Ziet er naar mijn idee wel goed uit. Het valt me nu alleen wel op dat er op veel plekken nog geen commentaar staat. Als je dit nog zou doen is dat geweldig

2022-12-15 14:48 UTC, FrancaBaars commented on web/bin/db_node_controller.js
>  class NodeController {
Willen we in de api calls nog commentaar per methode wat elke methode doet? Op dit moment is dat namelijk niet zo. En ik denk dat het dan wel wat duidelijker wordt.

2022-12-15 14:48 UTC, FrancaBaars commented on web/public/assets/scripts/changePoiNode.js
> +poiTypeDropdown.addEventListener("change", () => {
Commentaar toevoegen van wat deze methode doet graag.

2022-12-15 14:48 UTC, FrancaBaars commented on web/public/assets/scripts/changePoiNode.js
> +    console.log(poiTypeDropdown.value);
Is deze console.log nog nodig?

2022-12-15 14:48 UTC, FrancaBaars commented on web/public/assets/scripts/swal.js
> +        title: "Route aanmaken is mislukt",
De naam van dit ding is failed_create_poi maar dan is hier de zin "route aanmaken is mislukt" dit klopt niet helemaal

2022-12-15 14:48 UTC, FrancaBaars commented on web/routes/api/routes/route.api.js
> +removeGeoJsonMarkers = (geojson) => {
In dit bestand ook graag commentaar toevoegen aan de methodes. Ik weet niet of je hier bij andere bestanden er op hebt gelet, maar er moet wel commentaar bij.

2022-12-16 08:45 UTC, FrancaBaars requested changes
Paar kleine dingen aanpassen en dan werkt het beter

2022-12-16 08:45 UTC, FrancaBaars commented on web/middleware/schemas.js
> +                )
Regel 93 graag de beschrijving meer tekens laten hebben

2022-12-16 08:45 UTC, FrancaBaars commented on web/routes/form/form.route.js
>  const multer = require("multer");
Op dit moment is een audio bestand en een afbeelding verplicht, graag dan aangeven in de form dat dat zo is.

2022-12-16 08:53 UTC, elementer23 requested changes

2022-12-16 08:53 UTC, elementer23 commented on web/bin/db_route_controller.js
> +                    `/route-poi-editor/${new_route.id}/1`
wat de heck is dit, je set een nieuw route id en doe je daarna nog 1 of zo?

2022-12-16 08:53 UTC, elementer23 commented on web/public/assets/styles/style.css
>      position: relative;
waar is al je code conventie commentaar

2022-12-16 08:53 UTC, elementer23 commented on web/routes/frontend/frontend.route.js
> +        if (feature > 0 && feature < route.route.features.length) {
doet dat stukje na de && uberhaupt wel iets neem aan van wel, maar feature heeft een aantal params. je kijkt alleen naar de lengte van de route features en kijkt of het groter is dan de feature. Of is feature zelf een nummer?

2022-12-16 08:53 UTC, elementer23 commented on web/routes/frontend/frontend.route.js
> +        if (feature > 0 && feature < route.route.features.length) {
nog maals idk

2022-12-16 08:53 UTC, elementer23 commented on web/views/route-poi-editor.pug
> +                                    input(type="number" min=0 placeholder="Nummer..." name="radius" required).block.p-1.font-normal.w-full.mb-4
tailwind is in principe ook css hoeft niet per se. Maar volgens de code conventie moet je het in principe wel uitleggen. of commentaar uitvoeren

2022-12-16 14:18 UTC, elementer23 approved these changes

2022-12-18 15:08 UTC, FrancaBaars requested changes
Er gaat iets fout in de regex van de beschrijving van een route. 
Ik kan ook een gpx bestand van een route met poi's niet uploaden, dan geeft hij ook een fout melding. Hierdoor kan ik niet testen of de poi toevoegen goed gaat.

2022-12-19 09:25 UTC, FrancaBaars approved these changes

2022-12-19 09:26 UTC, merged